apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgress-pod
      app: demo-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgress-pod
        app: demo-voting-app
    
    spec:
      containers:
        - name: postgress
          image: postgres:9.4
          ports:
            - containerPort: 5432
    